site_name: jlheflin's Tips and Tricks
site_url: https://jlheflin.github.io
nav:
  - 'Another one': about.md
  - 'TOP LEVEL CAT':
    - index.md
    - TEST: about.md
    - 'BOTTOM LEVEL CAT':
      - About: about.md
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
