site_name: jlheflin's Tips and Tricks
site_url: https://jlheflin.github.io
nav:
  - Home: index.md
  - About: about.md
  - Programs:
    - programs/index.md
    - Computational Chemistry:
      - programs/computational_chemistry/index.md
    - Shells:
      - programs/shells/index.md
  - Tools:
    - tools/index.md
  - Procedures:
    - procedures/index.md
  - Projects:
    - projects/index.md
  - Notes:
    - notes/index.md

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.indexes

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascript/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
