site_name: jlheflin's Tips and Tricks
site_url: https://jlheflin.github.io
nav:
  - 'NWChemEx Install Guide': nwchemex_install_instructions.md
  - 'Spack NWChem Install Guide': spack_nwchem_install_guide.md

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.indexes

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascript/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
